### PR TITLE
Standalone `XmlAppendingTransformerTest`

### LINKED ISSUE #808: Bundling XML files from dependencies' META-INF folder into the shadow JAR's META-INF
### Shadow Version
7.1.2
### Gradle Version
7.4
### Expected Behavior
The shadowJar command automatically takes every file from the dependencies' META-INF's to add them to the final JAR, merging them on the way.
### Actual Behavior
Failed to import the dependencies' META-INF/plugin.xml into the JAR's XML file.

### Gradle Build Script(s)
shadowJar {
    transform(com.github.jengelman.gradle.plugins.shadow.transformers.XmlAppendingTransformer.class) {
        resource = 'META-INF/plugin.xml'
    }
}

### PR DESCRIPTION
**Pull request by Goooler**
Closes #808.

### CODE REVIEW

File: src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/XmlAppendingTransformerTest.kt [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+      transform<XmlAppendingTransformer>(
+        shadowJarBlock = fromJar(pluginJar),
+      ),
+    )
+
+    run(shadowJarTask)
+
+    val content = outputShadowJar.use { it.getContent(xmlEntry) }.trimIndent()
+    assertThat(content).isEqualTo(xmlContent)
+  }
```
Comment (Goooler) [inline src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/XmlAppendingTransformerTest.kt:74]: This looks useless.

Comment (Goooler) [reply src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/XmlAppendingTransformerTest.kt:74]: Remove it in #1243.
