### PR TITLE
Restore Develocity Build Scan integration

### LINKED ISSUE #907: Plugin is incompatible with isolated projects feature
Please check the [User Guide](http://imperceptiblethoughts.com/shadow) before submitting "how do I do 'x'?" questions!

### Shadow Version

8.1.1

### Gradle Version

8.5

### Expected Behavior

Plugin does not violate [project isolation](https://gradle.github.io/configuration-cache/) constraints, no errors are raised when a project to which the plugin is applied which also enables project isolation is being imported into IntelliJ.

### Actual Behavior

An error is thrown when a project to which the plugin is applied which also enables project isolation is being imported into IntelliJ. The following stacktrace is present in the configuration cache report generated upon the error:
```
org.gradle.api.InvalidUserCodeException: Cannot access project ':' from project ':services'
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:329)
	at com.github.jengelman.gradle.plugins.shadow.ShadowPlugin$_apply_closure1.doCall$original(ShadowPlugin.groovy:24)
	at com.github.jengelman.gradle.plugins.shadow.ShadowPlugin$_apply_closure1.doCall(ShadowPlugin.groovy)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at com.github.jengelman.gradle.plugins.shadow.ShadowPlugin.apply(ShadowPlugin.groovy:15)
	at com.github.jengelman.gradle.plugins.shadow.ShadowPlugin.apply(ShadowPlugin.groovy)
	at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultPluginContainer.java:70)
	....
```

That's because [the plugin calls `getPlugins()` on the `rootProject` instance from sub projects](https://github.com/johnrengelman/shadow/blob/2f94a2558023b208ffb840471281703cb2c9b222/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowPlugin.groovy#L24) which is not compatible with isolated projects.

One fix for this problem would be to check if `com.gradle.enterprise` plugin is applied to the `Settings` object [(because that's what you should be applying the plugin in newer versions to according to the docs](https://docs.gradle.com/enterprise/gradle-plugin/#gradle_6_x_and_later)) rather than the root project object but sadly you cannot get to an instance of `Settings` from an instance of `Project`. Another fix would be for the `com.gradle.enterprise` plugin to register itself as a plugin on `Gradle` instance (to which you can get from an instance of `Project`) together with an instance of `GradleEnterpriseExtension` but for that we would probably need core Gradle team to change the implementation as I don't believe this is happening now (hard to tell given `com.gradle.enterprise` is closed source).

As a workaround, I will reverse engineer `com.github.jengelman.gradle.plugins.shadow.ShadowPlugin` as I have a convention plugin applying it in my project and simply boil it down to:
```
project.with {
    plugins.apply(ShadowBasePlugin)
    plugins.withType(JavaPlugin) {
        plugins.apply(ShadowJavaPlugin)
    }
}
```
Nevertheless, it would be good if this plugin was compatible with project isolation out of the box.

### PR DESCRIPTION
**Pull request by gabrielfeo**
Restore the Develocity Build Scan integration, which adds custom values to Build Scans about the execution of Shadow tasks. It had been first disabled (#993) to resolve #907 for consumers enabling [Isolated Projects][1] (IP), then removed altogether (#1014). 

- Code is added similar to what was removed #1014, but with changes to migrate it to Kotlin (it was Groovy)
- The code is made IP-compatible by using the `buildScan` extension that's available in subprojects (cd9c60071fa5af35a3bd82cd695c121c7ae34322), instead of the root project's extension. That was added in [Develocity Gradle plugin 4.0][2].
- A `compileOnly` dependency is added for `ShadowPlugin` to reference the `buildScan` extension class (that wasn't necessary in Groovy)
- Support for `com.gradle.enterprise` which was present in the original code is omitted. There's no version of that plugin supporting the `buildScan` extension in subprojects, thus adding custom values would have to take place in the root project (not IP-compatible). That plugin is replaced by `com.gradle.develocity` and no longer maintained.

Currently, the custom values added by this PR are an example, since `ShadowStats` was also removed recently (#1264).

### Tests

A functional test around IP compatibility is added to demonstrate that the fix works and to prevent future regressions.

- [Build Scan showing the test failing before the fix][3], reproducing the same error reported in the original issue (#907)
- [Build Scan showing the test passing after the fix][4]

[1]: https://docs.gradle.org/current/userguide/isolated_projects.html
[2]: https://docs.gradle.com/develocity/gradle-plugin/current/#4_0
[3]: https://scans.gradle.com/s/r3yoxewbrtx5g/tests/task/:functionalTest/details/com.github.jengelman.gradle.plugins.shadow.IsolatedProjectsCompatibilityTest/applyToProjectWithIsolatedProjectsEnabled()?top-execution=1
[4]: https://scans.gradle.com/s/y2dxeizmtcobe/tests/task/:functionalTest/details/com.github.jengelman.gradle.plugins.shadow.IsolatedProjectsCompatibilityTest/applyToProjectWithIsolatedProjectsEnabled()?top-execution=1

---

- [x] [CHANGELOG](https://github.com/GradleUp/shadow/blob/main/docs/changes/README.md)'s "Unreleased" section has been updated, if applicable.

### CODE REVIEW

**Comment by gabrielfeo** [comment]
Hi there 👋🏻 

This PR demonstrates that Develocity/Build Scan integration could be restored, but it's not clear to me if you'd like to restore `ShadowStats` as well or add different custom values. We could add actual custom values and also create more tests.

**Comment by Goooler** [comment]
Restoring `ShadowStats` is hard, and it hasn't been tested. I suspect there are numerous issues regarding its accuracy.

Actually, I don't have much interest in adding `ShadowStats` or Develocity integration back.

File: src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowPlugin.kt [hunk 1]
```diff
@@ -29,5 +31,36 @@ public abstract class ShadowPlugin : Plugin<Project> {
     // If the user applies shadow before those plugins. However, this is fine, because this was also
     // the behavior with the old plugin when applying in that order.
     apply(LegacyShadowPlugin::class.java)
+
+    withId("com.gradle.develocity") {
```
Comment (wolfs) [inline src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowPlugin.kt]: ❌ I don't think this will work since the Develocity plugin isn't applied to subprojects. The test doesn't detect this, because it doesn't have a sub-project. I suggest checking whether an extension with the name `develocity` is present at the project level.

**Review by wolfs — CHANGES_REQUESTED** [review]

File: src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginTest.kt [hunk 2]
```diff
@@ -779,6 +781,36 @@ class JavaPluginTest : BasePluginTest() {
...
+    settingsScriptPath.writeText(
+      """
+        plugins {
+          id 'com.gradle.develocity'
+        }
+        develocity {
+          buildScan {
+            termsOfUseUrl = 'https://gradle.com/terms-of-service'
+            termsOfUseAgree = 'yes'
+            publishing.onlyIf { true }
```
Comment (wolfs) [inline src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginTest.kt]: ❌ I don't think it is a good idea for the test to publish a build scan to scans.gradle.com. Should we dump the scan file instead.

File: src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowPlugin.kt (hunk 1 above)
Comment (gabrielfeo) [reply src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/ShadowPlugin.kt]: Thank you, @wolfs. You're correct. I've changed the code to your suggestion in d7025200f941f113ea4e9e5c6ac7c1be33869ac5.

File: src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/BuildScanIntegration.kt [hunk 3]
```diff
@@ -0,0 +1,18 @@
+package com.github.jengelman.gradle.plugins.shadow.internal
+
+import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
+import com.gradle.develocity.agent.gradle.DevelocityConfiguration
+import org.gradle.api.Project
+
+public fun Project.addBuildScanCustomValues() {
+  extensions.configure<DevelocityConfiguration>("develocity") {
```
Comment (wolfs) [inline src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/BuildScanIntegration.kt]: ❓ Why do you obtain the extension again, instead of casing the one you got via `project.extensions.findByName("develocity")`?

File: src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/BuildScanIntegration.kt [hunk 4]
```diff
@@ -0,0 +1,18 @@
...
+    val buildScan = it.buildScan
+    val shadowTasks = tasks.withType(ShadowJar::class.java)
+    shadowTasks.configureEach { task ->
+      buildScan.buildFinished {
```
Comment (wolfs) [inline src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/BuildScanIntegration.kt]: This is now happening when the shadow task is being configured. I suppose you want to add it only when the shadow task has been executed. Was this like this before?

File: src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/BuildScanIntegration.kt (hunk 3 above)
Comment (gabrielfeo) [reply src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/BuildScanIntegration.kt]: It seemed a (strong typing) code smell to take an `Any` argument here and cast it. On the other hand, I wouldn't be able to take a `DevelocityConfiguration`-typed argument here because that class is in a `compileOnly` dependency, meaning I couldn't reference it as eagerly as in the plugin class if it's not present at runtime after all (783860bf228a6b110c9d2bc9a507e5c970c7423c).

To still address your comment though, I removed the extension lookup that was in the plugin and kept this one (826bb4103f678f09654f8a3e607075c065165bef).

File: src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/BuildScanIntegration.kt (hunk 4 above)
Comment (gabrielfeo) [reply src/main/kotlin/com/github/jengelman/gradle/plugins/shadow/internal/BuildScanIntegration.kt]: The original code was slightly different. It added a single `buildFinished` callback and iterated on each tasks [inside](https://github.com/GradleUp/shadow/pull/1014/files#diff-4f688def42f06583701e7481cc7f29c906b6c9cf0808dac578d46d6300781ec9L46) that callback, but that requires serializing `Project` for configuration cache as part of that callback, which isn't supported. It also achieved what you propose by using `didWork`, which I also added (34a18ac6385d03dd71efe83a0327a799ebd3b71e), but it won't work here if I iterate on tasks at configuration time (and keep CC compatibility)

File: src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginTest.kt (hunk 2 above)
Comment (gabrielfeo) [reply src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginTest.kt]: While the test doesn't currently depend on/assert about scan publishing having succeeded, I think that's a good point. I changed it to dump the scan file in d639b8a076d4b62d37c48ed2f6bfda184b212d34.

Comment (Goooler) [reply src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/JavaPluginTest.kt]: Removing `develocity` block in e829b8a02aae585024b4f776c6dacfa0926ae290.

**Comment by gabrielfeo** [comment]
> Restoring ShadowStats is hard, and it hasn't been tested. I suspect there are numerous issues regarding its accuracy.
> 
> Actually, I don't have much interest in adding ShadowStats or Develocity integration back.

@Goooler, aside from `ShadowStats`, is there any metadata or measurements you think would be useful to surface in a Build Scan that we could help implement?

The benefit for users would be, when viewing a single Build Scan, this metadata giving insights into work shadow did without having to add to the console log. Also, when using a Develocity server to process several Build Scans at scale, tracking certain measurements can help find bottlenecks or unwanted usages across several projects (e.g. dependencies and configurations as the integration logged before), fix them and track the impact.

**Comment by Goooler** [comment]
I believe this is a secondary feature with low priority. If you really want to reintroduce it, please include it in the follow-ups and ensure it is thoroughly tested.

**Comment by Goooler** [comment]
@wolfs Any comments?

**Comment by Goooler** [comment]
CC @wolfs
