### PR TITLE
Deprecate ShadowExtension.component

### LINKED ISSUE #945: Configuring publishing before shadowJar publishes jar with wrong configuration
Originally reported in https://github.com/Goooler/shadow/issues/106 

I discovered that my project was configuring publishing before the actual shadowJar, which was causing the wrong classifier to get picked up by the shadow plugin. Is this a reasonable situation that could be improved with lazy evaluation, or should I restructure my build file to configure shadowJar first?

### Shadow Version
8.1.4-8.1.8 of Goooler's fork

### Gradle Version
8.8

### Expected Behavior
The archive published has the classifier that I specified in shadowJar archiveClassifier

### Actual Behavior
The archiveClassifier is all

### Gradle Build Script(s)
See this modified unit test in my fork, which is failing: 
https://github.com/gharris1727/shadow/blob/772444c88e9fbec864364fdc5de6134bb4ccfa2f/src/test/groovy/com/github/jengelman/gradle/plugins/shadow/PublishingSpec.groovy#L81-L127 

### Content of Shadow JAR (jar tf <jar file> - post link to GIST if too long)
N/A

### PR DESCRIPTION
**Pull request by Goooler**
Closes #945.

---

- [x] [CHANGELOG](src/docs/changes/README.md)'s "Unreleased" section has been updated, if applicable.

### CODE REVIEW

File: src/test/groovy/com/github/jengelman/gradle/plugins/shadow/PublishingSpec.groovy [hunk 1]
```diff
@@ -116,14 +112,23 @@ class PublishingSpec extends PluginSpecification {
...
         run('publish')
 
         then:
-        File publishedFile = publishingRepo.rootDir.file('shadow/maven-all/1.0/maven-all-1.0-my-classifier.my-ext').canonicalFile
-        assert publishedFile.exists()
+        def publishedFiles = publishingRepo.rootDir.file('shadow/maven-all/1.0/').canonicalFile
+                .listFiles()
+                .findAll { it.exists() }
+                .collect { it.name }
+        assert publishedFiles.contains('maven-all-1.0-my-classifier.my-ext')
```
Comment (Goooler) [inline src/test/groovy/com/github/jengelman/gradle/plugins/shadow/PublishingSpec.groovy:131]:
```
[
  maven-all-1.0-all.my-ext.sha256, 
  maven-all-1.0.pom.sha512, 
  maven-all-1.0.pom.sha1, 
  maven-all-1.0-all.my-ext.md5,
  maven-all-1.0.pom, 
  maven-all-1.0.pom.sha256, 
  maven-all-1.0.pom.md5, 
  maven-all-1.0-all.my-ext.sha512, 
  maven-all-1.0-all.my-ext, 
  maven-all-1.0-all.my-ext.sha1,
]
```

Comment (Goooler) [reply src/test/groovy/com/github/jengelman/gradle/plugins/shadow/PublishingSpec.groovy:134]: 413f5e39375bdb7e948c912f5be61a0713a5cf11

Comment (Goooler) [reply src/test/groovy/com/github/jengelman/gradle/plugins/shadow/PublishingSpec.groovy]: dc4f895aed316c6d7777037579e7728aef43a77c

**Comment by Goooler** [comment]
@johnrengelman Thanks for the prototype! I believe this is what you expected.
