### PR TITLE
Fix using `ApacheNoticeResourceTransformer` without `projectName`

### LINKED ISSUE #1626: ApacheNoticeResourceTransformer cannot be used without specifying project name
### Expected and Results

If my project shades Apache 2.0 dependencies and is under a different license, I want to merge NOTICE files without including my project in the final NOTICE.

```kts
tasks.named<ShadowJar>("shadowJar") {
    transform(ApacheNoticeResourceTransformer::class.java) {
        addHeader.set(false)
    }
}
```
This configuration fails with the following error:
```
java.lang.IllegalStateException: The value for property 'copyright' is final and cannot be changed any further.
```

### Related environment and versions

_No response_

### Reproduction steps

Here is an example test case you can add to [TransformersTest.kt](https://github.com/GradleUp/shadow/blob/700472a1803be43659a7538de1693fb685b7dcfa/src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/TransformersTest.kt) to reproduce this issue.

```kts
@Test
fun apacheNoticeTransformerWithRealDependencies() {
  projectScript.appendText(
    """
    dependencies {
      implementation 'org.apache.commons:commons-dbcp2:2.13.0'
      implementation 'org.apache.commons:commons-pool2:2.12.0'
    }
    $shadowJarTask {
      transform(${ApacheNoticeResourceTransformer::class.java.name}) {
        addHeader = false
      }
    }
  """.trimIndent(),
  )

  run(shadowJarPath) // This will fail
}
```

### Anything else?

The same configuration will not fail using the [maven-shade-plugin](https://github.com/apache/maven-shade-plugin).

For example:
```xml
<dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-dbcp2</artifactId>
    <version>2.13.0</version>
</dependency>
<dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-pool2</artifactId>
    <version>2.12.0</version>
</dependency>
...
<transformer implementation="org.apache.maven.plugins.shade.resource.ApacheNoticeResourceTransformer">
    <addHeader>false</addHeader>
</transformer>
```

### PR DESCRIPTION
**Pull request by Goooler**
Closes #1626.

---

- [x] [CHANGELOG](https://github.com/GradleUp/shadow/blob/main/docs/changes/README.md)'s "Unreleased" section has been updated, if applicable.

### CODE REVIEW

File: src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/TransformersTest.kt [hunk 1]
```diff
@@ -211,6 +211,65 @@ class TransformersTest : BaseTransformerTest() {
...
+        """
+        Apache Commons Pool
+        Copyright 2001-2025 The Apache Software Foundation
+
+        This product includes software developed at
+        The Apache Software Foundation (https://www.apache.org/).
+
+        Apache Commons DBCP
+        Copyright 2001-2024 The Apache Software Foundation
+        """.trimIndent(),
```
Comment (Goooler) [inline src/functionalTest/kotlin/com/github/jengelman/gradle/plugins/shadow/transformers/TransformersTest.kt:268]: @xEricL, please check if the output notice is correct?
